// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8D2E2AMnam4wdDkn0H9LHpcKjscPjfIo',
    appId: '1:156324020032:web:696529653b8923a89dc4a5',
    messagingSenderId: '156324020032',
    projectId: 'grocery-34bd8',
    authDomain: 'grocery-34bd8.firebaseapp.com',
    storageBucket: 'grocery-34bd8.appspot.com',
    measurementId: 'G-0L52LDEFV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LqdFkvVngK22Qh4ekle_SgR9Cm5bcFY',
    appId: '1:156324020032:android:26ecc1970225ea829dc4a5',
    messagingSenderId: '156324020032',
    projectId: 'grocery-34bd8',
    storageBucket: 'grocery-34bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-nHgE4ItNGHA6Kd7xYO5_VYlmEhzGwo',
    appId: '1:156324020032:ios:fc84a19b53d2d4b09dc4a5',
    messagingSenderId: '156324020032',
    projectId: 'grocery-34bd8',
    storageBucket: 'grocery-34bd8.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-nHgE4ItNGHA6Kd7xYO5_VYlmEhzGwo',
    appId: '1:156324020032:ios:f47d274bbe6173819dc4a5',
    messagingSenderId: '156324020032',
    projectId: 'grocery-34bd8',
    storageBucket: 'grocery-34bd8.appspot.com',
    iosBundleId: 'com.example.grocery.RunnerTests',
  );
}
